- id: gen_z
  canonicalName: Generation Z
  aliases:
    - Gen Z
    - Zoomers
    - Post-Millennials
    - iGen

- id: millennial
  canonicalName: Millennials
  aliases:
    - Gen Y
    - Generation Y
    - Echo Boomers

- id: gen_x
  canonicalName: Generation X
  aliases:
    - Gen X
    - MTV Generation
    - Latchkey Generation

- id: baby_boomer
  canonicalName: Baby Boomers
  aliases:
    - Boomers
    - Gen Boomer
    - Post-Silent Generation

- id: silent
  canonicalName: Silent Generation
  aliases:
    - The Silent Generation
    - Traditionalists
    - Radio Babies
